
#server.jsp-servlet.init-parameters.development=true
spring:
  datasource:
    url: jdbc:h2:~/jpashop
    username: sa
    passwd:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       show_sql: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace